FROM node:26.5.0-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY . .
RUN npm run build

FROM nginx:1.31.3-alpine
RUN adduser -D appuser
USER appuser
COPY --from=build /app/dist /dist

VOLUME /usr/share/nginx/html
CMD ["cp", "-r", "/dist/.", "/usr/share/nginx/html/"]
