"""add_feedback_table

Revision ID: 6a8afe17ea7b
Revises: b7f3e1d20a4c
Create Date: 2026-05-26 11:16:06.481913
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6a8afe17ea7b"
down_revision: str | None = "b7f3e1d20a4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("theme", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "google_credentials_telegram_user_id_key", "google_credentials", type_="unique"
    )
    op.drop_index(
        "ix_google_credentials_telegram_user_id", table_name="google_credentials"
    )
    op.create_index(
        op.f("ix_google_credentials_telegram_user_id"),
        "google_credentials",
        ["telegram_user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_google_credentials_telegram_user_id"), table_name="google_credentials"
    )
    op.create_index(
        "ix_google_credentials_telegram_user_id",
        "google_credentials",
        ["telegram_user_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "google_credentials_telegram_user_id_key",
        "google_credentials",
        ["telegram_user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("feedback")
    # ### end Alembic commands ###
