#!/usr/bin/env python3
"""Generate VitePress fragments from OpenAPI and the platform registry.

Writes under docs/generated/ (committed). Run via `make docs-generate`.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SERVER_DIR = REPO_ROOT / "server"
GENERATED_DIR = REPO_ROOT / "docs" / "generated"
PUBLIC_DIR = REPO_ROOT / "docs" / "public"
TEST_ENV = SERVER_DIR / "tests" / ".env.test"
COMPOSE_FILE = REPO_ROOT / "docker-compose.yml"

GENERATED_BANNER = (
    "<!-- Generated by scripts/generate_docs.py — do not edit by hand. -->\n"
    "<!-- Run: make docs-generate -->\n\n"
)

_PLATFORM_HEADER = (
    "| Slug | Category | API prefix | Admin route | Public |"
    " Public route | Capabilities |"
)
_PLATFORM_DIVIDER = (
    "|------|----------|------------|-------------|"
    "--------|--------------|--------------|"
)
_PLATFORM_ROW = (
    "| {slug} | {category} | `{api}` | `{admin}` |"
    " {public} | {proute} | {caps} |"
)


def _esc_cell(value: str) -> str:
    """Escape pipe characters for markdown table cells."""
    return value.replace("|", "\\|").replace("\n", " ")


def _log(message: str) -> None:
    """Write a progress line to stdout (CLI tool)."""
    sys.stdout.write(f"{message}\n")


def _compose_service_names(compose_path: Path) -> list[str]:
    """Parse top-level Compose service names without PyYAML."""
    if not compose_path.is_file():
        return []
    names: list[str] = []
    in_services = False
    for line in compose_path.read_text(encoding="utf-8").splitlines():
        if line.startswith("services:"):
            in_services = True
            continue
        if not in_services:
            continue
        if line and not line[0].isspace() and not line.startswith("#"):
            break
        match = re.match(r"^  ([A-Za-z0-9_-]+):\s*(?:#.*)?$", line)
        if match:
            names.append(match.group(1))
    return names


def _write_architecture_inventory() -> None:
    """Emit platform registry + Compose service inventory markdown."""
    sys.path.insert(0, str(SERVER_DIR))
    from app.platform.registry import PLATFORM_SERVICES

    lines = [
        GENERATED_BANNER.rstrip(),
        "",
        "# Architecture inventory",
        "",
        "Auto-generated from "
        "[`server/app/platform/registry.py`](../../server/app/platform/registry.py) "
        "and top-level services in "
        "[`docker-compose.yml`](../../docker-compose.yml).",
        "",
        "## Platform services",
        "",
        _PLATFORM_HEADER,
        _PLATFORM_DIVIDER,
    ]
    for svc in PLATFORM_SERVICES:
        lines.append(
            _PLATFORM_ROW.format(
                slug=_esc_cell(svc.slug),
                category=_esc_cell(svc.category),
                api=_esc_cell(svc.api_prefix),
                admin=_esc_cell(svc.admin_route),
                public="yes" if svc.public else "no",
                proute=_esc_cell(svc.public_route or "—"),
                caps=_esc_cell(", ".join(svc.capabilities)),
            )
        )

    compose_names = _compose_service_names(COMPOSE_FILE)
    lines.extend(
        [
            "",
            "## Compose services (`docker-compose.yml`)",
            "",
        ]
    )
    if compose_names:
        lines.append(", ".join(f"`{name}`" for name in compose_names))
    else:
        lines.append("_No services parsed._")
    lines.append("")

    out = GENERATED_DIR / "architecture-inventory.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _log(f"wrote {out.relative_to(REPO_ROOT)}")


def _endpoint_rows(schema: dict[str, Any]) -> list[tuple[str, str, str, str]]:
    """Flatten OpenAPI paths into (method, path, tags, summary) rows."""
    rows: list[tuple[str, str, str, str]] = []
    paths = schema.get("paths") or {}
    for path, methods in sorted(paths.items()):
        if not isinstance(methods, dict):
            continue
        for method, operation in sorted(methods.items()):
            if method.startswith("x-") or not isinstance(operation, dict):
                continue
            if method.upper() not in {
                "GET",
                "POST",
                "PUT",
                "PATCH",
                "DELETE",
                "HEAD",
                "OPTIONS",
            }:
                continue
            tags = ", ".join(operation.get("tags") or [])
            summary = operation.get("summary") or operation.get("operationId") or ""
            rows.append((method.upper(), path, tags, str(summary)))
    return rows


def _write_openapi_artifacts() -> None:
    """Export OpenAPI JSON and a markdown endpoint table."""
    os.environ.setdefault("GLORNG_ENV_FILE", str(TEST_ENV))
    if str(SERVER_DIR) not in sys.path:
        sys.path.insert(0, str(SERVER_DIR))

    # Import after env is set so Settings picks up the test file.
    from app.main import create_app
    from app.settings import get_settings

    get_settings.cache_clear()
    app = create_app()
    schema = app.openapi()

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)

    openapi_path = GENERATED_DIR / "openapi.json"
    openapi_json = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    openapi_path.write_text(openapi_json, encoding="utf-8")
    (PUBLIC_DIR / "openapi.json").write_text(openapi_json, encoding="utf-8")
    _log(f"wrote {openapi_path.relative_to(REPO_ROOT)}")
    _log(f"wrote {(PUBLIC_DIR / 'openapi.json').relative_to(REPO_ROOT)}")

    rows = _endpoint_rows(schema)
    lines = [
        GENERATED_BANNER.rstrip(),
        "",
        "# API endpoints",
        "",
        "Auto-generated from the FastAPI OpenAPI schema "
        "(`create_app().openapi()`). Download the raw schema: "
        "[openapi.json](/openapi.json).",
        "",
        f"**{len(rows)}** operations.",
        "",
        "| Method | Path | Tags | Summary |",
        "|--------|------|------|---------|",
    ]
    for method, path, tags, summary in rows:
        lines.append(
            f"| `{method}` | `{_esc_cell(path)}` | {_esc_cell(tags)} | "
            f"{_esc_cell(summary)} |"
        )
    lines.append("")

    endpoints_path = GENERATED_DIR / "api-endpoints.md"
    endpoints_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _log(f"wrote {endpoints_path.relative_to(REPO_ROOT)}")


def main() -> int:
    """Generate all documentation artifacts."""
    if not TEST_ENV.is_file():
        sys.stderr.write(f"missing test env: {TEST_ENV}\n")
        return 1

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    _write_architecture_inventory()
    _write_openapi_artifacts()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
